NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.org2.sxf.bjut.cn-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.org2.sxf.bjut.cn-cert.pem
    OrganizationalUnitIdentifier: peer
